suites:
    kawaii_suite:
        namespace: cdcchen\psr3
        psr4_prefix: cdcchen\psr3
        spec_prefix: spec
        src_path: %paths.config%/src
        spec_path: %paths.config%

formatter.name: progress
code_generation: true
stop_on_failure: true